image: Visual Studio 2022

install:
  - ps: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
  - ps: ./dotnet-install.ps1 -Channel 8.0.1xx -Quality GA

init:
- git config --global core.autocrlf true

build_script:
- ps: dotnet pack -c Release -o artifacts

test_script:
- ps: dotnet test

artifacts:
- path: artifacts\*.nupkg

deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  on:
    appveyor_repo_tag: true
  api_key:
    secure: Sw166ShB7/LHE0A5xSbRN1Ul5Uk6/crK9Yw0cdzIU4GZOGOc14l/ae3x5IVtGyUl
  skip_symbols: true